// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "./components/Nav";
import { Toaster } from "@/components/ui/sonner";
import UserContext from "@/context/userContext"; // Ensure this is correctly imported
import UserProvider from "@/context/userProvider"; // Fix: Import UserProvider (with uppercase U)

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Wrap everything with UserProvider */}
        <UserProvider>  {/* Fix: Capitalize UserProvider */}
          <Toaster />
          <Nav />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
